# This is a config for E2B sandbox template.
# You can use 'template_id' (0qwufpwh66owfdikcyof) or 'template_name (server-worker) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='server-worker')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'server-worker' })

memory_mb = 2_048
dockerfile = "server.Dockerfile"
template_name = "server-worker"
template_id = "0qwufpwh66owfdikcyof"
