# This is a config for E2B sandbox template.
# You can use 'template_id' (ll2a9wqh9ekdor6t4t3n) or 'template_name (worker-sandbox) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='worker-sandbox')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'worker-sandbox' })

dockerfile = "Dockerfile.e2b"
template_name = "worker-sandbox"
template_id = "ll2a9wqh9ekdor6t4t3n"
