# This is a config for E2B sandbox template.
# You can use 'template_id' (9hmm93g52nuzeqqlyyox) or 'template_name (terminal-sandbox) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='terminal-sandbox')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'terminal-sandbox' })

dockerfile = "Dockerfile"
template_name = "terminal-sandbox"
template_id = "9hmm93g52nuzeqqlyyox"
